apiVersion: networking.k8s.io/v1 # k8s >= 1.22 必须 v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: nginx.test.com
  http:
    paths:
    - backend:
        service:
          name: nginx-service
          port:
            number: 80
      path: /
      pathType: ImplementationSpecific